"""
NBM NBP (probabilistic) text bulletin client.

WHAT THIS GETS US
-----------------
Per-station forecast distributions for max/min temperature, in the form of:
    TXNMN = mean
    TXNSD = standard deviation
    TXNP1 = 10th percentile  (10% chance temp <= this value)
    TXNP2 = 25th percentile
    TXNP5 = 50th percentile  (median)
    TXNP7 = 75th percentile
    TXNP9 = 90th percentile

These are NOT a normal distribution we're guessing. They are NOAA's
post-processed, calibrated quantiles, generated by quantile mapping the
ensemble against the URMA analysis-of-record using a rolling 120-day
training sample. This is empirically what we want to bet against.

CYCLES & TIMING
---------------
NBP is fully populated at cycles 01Z, 07Z, 13Z, 19Z (4x/day).
Partial data is available at 00Z and 12Z. Other cycles are limited.
We poll the latest fully-populated cycle.

DATE/TIME ALIGNMENT WITH KALSHI
-------------------------------
Kalshi settles against the NWS Daily Climate Report (CLI), which uses
LOCAL STANDARD TIME (LST) for the daily reporting period - even during
daylight saving. The NBP bulletin's column header gives the UTC date/cycle
the value applies to:
  - Min temperature (TXN* in row labeled at 12Z column) covers the
    overnight period ending around morning local time.
  - Max temperature (TXN* in row labeled at 00Z column) covers the
    daytime period of the previous local calendar day.

In practice, for CONUS:
  - The 00Z forecast hour for date D corresponds to the daytime high
    of LST date D-1.
  - The 12Z forecast hour for date D corresponds to the overnight low
    that ends the morning of LST date D.

We expose this as `local_max_date` / `local_min_date` on each forecast
column so the caller doesn't have to think about it.

PARSING
-------
The bulletin is a fixed-width text file. Each line starts with a 5-char
element name, then a series of pipe-separated columns. We anchor on the
"UTC" header row to find column boundaries.

URL
---
Single-station bulletins:
  https://nomads.ncep.noaa.gov/pub/data/nccf/com/blend/prod/blend.YYYYMMDD/CC/text/blend_nbptx.tCCz

The file contains ALL stations concatenated. We grep for the station's
ICAO followed by " NBM " on the header line.

A more reliable and lower-bandwidth alternative is the per-station HTTP
endpoint at https://sats.nws.noaa.gov/~nbm/nbm_text but it has rate limits
and is described as experimental. We use NOMADS as primary.
"""
from __future__ import annotations

import datetime as dt
import io
import logging
import re
from dataclasses import dataclass
from typing import Optional

import requests

log = logging.getLogger(__name__)

NOMADS_BASE = "https://nomads.ncep.noaa.gov/pub/data/nccf/com/blend/prod"
DEFAULT_TIMEOUT = 30
USER_AGENT = "kalshi-weather-bot/0.1 (jpmccaffery@gmail.com)"

# NBP cycles with full element coverage.
FULL_NBP_CYCLES = (1, 7, 13, 19)


class NBMError(Exception):
    pass


@dataclass
class TempPercentiles:
    """The forecast distribution for one (station, target_date, kind=high|low)."""
    station: str
    kind: str             # "high" or "low"
    target_date: dt.date  # LST calendar date this temp applies to
    cycle: dt.datetime    # The model run that produced this forecast (UTC)
    fhr: int              # Forecast hour from cycle to validity
    mean: Optional[float]
    sd: Optional[float]
    p10: Optional[float]
    p25: Optional[float]
    p50: Optional[float]
    p75: Optional[float]
    p90: Optional[float]

    def is_complete(self) -> bool:
        return all(x is not None for x in
                   (self.p10, self.p25, self.p50, self.p75, self.p90))

    def is_sentinel(self) -> bool:
        """All percentiles are missing (-99 sentinel), meaning the forecast
        horizon is too short for the ensemble to provide a distribution.
        The event is essentially already determined."""
        return all(x is None for x in
                   (self.p10, self.p25, self.p50, self.p75, self.p90))


class NBMClient:
    def __init__(self, user_agent: str = USER_AGENT,
                 timeout: int = DEFAULT_TIMEOUT,
                 session: Optional[requests.Session] = None):
        self._session = session or requests.Session()
        self._headers = {"User-Agent": user_agent}
        self._timeout = timeout
        # Cache the full-bulletin text per (date,cycle) since one fetch
        # covers all 39 stations.
        self._bulletin_cache: dict[tuple[dt.date, int], str] = {}

    def latest_full_cycle(self, now_utc: Optional[dt.datetime] = None
                          ) -> tuple[dt.date, int]:
        """The most recent (date, cycle) that should have complete NBP data."""
        now = now_utc or dt.datetime.now(dt.timezone.utc)
        # NBP is typically available ~90 minutes after the cycle hour.
        # Allow 2h to be safe.
        cutoff = now - dt.timedelta(hours=2)
        date = cutoff.date()
        hour = cutoff.hour
        candidates = [c for c in FULL_NBP_CYCLES if c <= hour]
        if candidates:
            return date, max(candidates)
        # Wrap around to the previous day's last cycle.
        return date - dt.timedelta(days=1), max(FULL_NBP_CYCLES)

    def _bulletin_url(self, date: dt.date, cycle: int) -> str:
        return (f"{NOMADS_BASE}/blend.{date:%Y%m%d}/{cycle:02d}/text/"
                f"blend_nbptx.t{cycle:02d}z")

    def fetch_bulletin(self, date: dt.date, cycle: int) -> str:
        key = (date, cycle)
        if key in self._bulletin_cache:
            return self._bulletin_cache[key]
        url = self._bulletin_url(date, cycle)
        r = self._session.get(url, headers=self._headers, timeout=self._timeout)
        if r.status_code != 200:
            raise NBMError(f"NBP fetch {url} -> {r.status_code}")
        self._bulletin_cache[key] = r.text
        return r.text

    def get_percentiles(self, station_icao: str,
                        date: Optional[dt.date] = None,
                        cycle: Optional[int] = None,
                        station_tz_offset: int = -5,
                        ) -> list[TempPercentiles]:
        """
        Return a list of TempPercentiles, one per forecast column for both
        max and min where data exists. station_tz_offset is the LST UTC
        offset (e.g. -5 EST, -6 CST, -8 PST).
        """
        if date is None or cycle is None:
            date, cycle = self.latest_full_cycle()
        text = self.fetch_bulletin(date, cycle)
        block = _extract_station_block(text, station_icao)
        if block is None:
            raise NBMError(f"Station {station_icao} not found in bulletin "
                           f"{date} {cycle:02d}Z")
        return _parse_nbp_block(block, station_icao,
                                cycle_dt=dt.datetime(
                                    date.year, date.month, date.day,
                                    cycle, tzinfo=dt.timezone.utc),
                                station_tz_offset=station_tz_offset)


# ---------- parsing ----------

# Header line example:
#   "KBWI   NBM V4.1 NBP GUIDANCE  5/01/2022  1300 UTC"
_HEADER_RE = re.compile(
    r"^(?P<icao>[A-Z0-9]{4})\s+NBM\s+V[\d.]+\s+NBP\s+GUIDANCE\s+"
    r"(?P<date>\d{1,2}/\d{1,2}/\d{4})\s+(?P<cycle>\d{4})\s+UTC")


def _extract_station_block(full_text: str, icao: str) -> Optional[str]:
    """Pull out one station's NBP block from the concatenated bulletin."""
    lines = full_text.splitlines()
    start = None
    for i, line in enumerate(lines):
        m = _HEADER_RE.match(line.lstrip())
        if m and m.group("icao") == icao.upper():
            start = i
            break
    if start is None:
        return None
    # The block runs until the next station's header or end of file.
    end = len(lines)
    for j in range(start + 1, len(lines)):
        m = _HEADER_RE.match(lines[j].lstrip())
        if m:
            end = j
            break
    return "\n".join(lines[start:end])


def _parse_columns(line: str) -> tuple[str, list[str]]:
    """
    NBP rows are formatted like:
      "TXNP5 55| 67 50| 62 48| 68 56| 74 ..."
    The first 5 chars are the element name. After that, the fixed format
    is space-separated values where every other value is followed by a '|'.
    We split on whitespace and pipes; missing values are -99 or -98 in v4.

    Returns (element_name, list_of_string_values).
    """
    line = line.lstrip()
    name = line[:5].strip()
    rest = line[5:]
    # Replace pipes with spaces and split.
    tokens = rest.replace("|", " ").split()
    return name, tokens


def _to_float(tok: str) -> Optional[float]:
    if tok in ("-99", "-98", "999", "998"):
        return None
    try:
        v = float(tok)
        # NBM v4 sentinel values.
        if v <= -98 or v >= 998:
            return None
        return v
    except ValueError:
        return None


def _parse_nbp_block(block: str, icao: str,
                     cycle_dt: dt.datetime,
                     station_tz_offset: int,
                     ) -> list[TempPercentiles]:
    """
    Parse the percentile rows from one station's NBP block and return
    a TempPercentiles for each (target_date, kind) pair.

    The DT/UTC/FHR header rows tell us, column-by-column, what date and
    UTC hour each value applies to. For temperature:
      - 00Z columns hold MAX temp for previous LST day's daytime.
      - 12Z columns hold MIN temp for the LST day ending that morning.
    """
    lines = block.splitlines()

    # Find the FHR row to anchor columns; walk subsequent rows we care about.
    rows: dict[str, list[Optional[float]]] = {}
    utc_hours: list[int] = []
    fhrs: list[int] = []

    for line in lines:
        prefix = line.lstrip()[:5].strip()
        if prefix == "UTC":
            _, toks = _parse_columns(line)
            utc_hours = [int(t) for t in toks]
        elif prefix == "FHR":
            _, toks = _parse_columns(line)
            fhrs = [int(t) for t in toks]
        elif prefix in ("TXNMN", "TXNSD", "TXNP1", "TXNP2",
                        "TXNP5", "TXNP7", "TXNP9"):
            _, toks = _parse_columns(line)
            rows[prefix] = [_to_float(t) for t in toks]

    if not utc_hours or not fhrs:
        raise NBMError(f"Could not find UTC/FHR header rows for {icao}")

    n = min(len(utc_hours), len(fhrs))
    # All temp rows should have the same column count; trim to common length.
    for k in list(rows.keys()):
        n = min(n, len(rows[k]))

    tz = dt.timezone(dt.timedelta(hours=station_tz_offset))
    out: list[TempPercentiles] = []
    for i in range(n):
        utc_h = utc_hours[i]
        fhr = fhrs[i]
        valid_utc = cycle_dt + dt.timedelta(hours=fhr)
        if valid_utc.hour != utc_h:
            # Sanity check; should never trigger.
            log.debug("col %d: cycle+fhr=%s but UTC col says %02dz",
                      i, valid_utc.isoformat(), utc_h)
        if utc_h == 0:
            # MAX temp: the daytime high of the previous LST calendar day.
            local_dt = valid_utc.astimezone(tz) - dt.timedelta(hours=1)
            target_date = local_dt.date()
            kind = "high"
        elif utc_h == 12:
            # MIN temp: overnight low ending this LST morning.
            local_dt = valid_utc.astimezone(tz)
            target_date = local_dt.date()
            kind = "low"
        else:
            continue

        out.append(TempPercentiles(
            station=icao,
            kind=kind,
            target_date=target_date,
            cycle=cycle_dt,
            fhr=fhr,
            mean=rows.get("TXNMN", [None]*n)[i],
            sd=rows.get("TXNSD", [None]*n)[i],
            p10=rows.get("TXNP1", [None]*n)[i],
            p25=rows.get("TXNP2", [None]*n)[i],
            p50=rows.get("TXNP5", [None]*n)[i],
            p75=rows.get("TXNP7", [None]*n)[i],
            p90=rows.get("TXNP9", [None]*n)[i],
        ))
    return out
