"""
Analysis of position returns vs time-of-purchase dimensions.

Loads from transaction_summary.csv (generated by transaction_summary.py).

Usage:
    python scripts/plot_return_by_hour.py                          # output/transaction_summary.csv
    python scripts/plot_return_by_hour.py output/paper/            # specific dir
    python scripts/plot_return_by_hour.py --csv path/to/file.csv   # explicit file
    python scripts/plot_return_by_hour.py --out output/plots/      # save location

Plots produced:
  return_by_hour.png      — scatter + mean bar by UTC hour of purchase
  return_by_staleness.png — scatter + mean bar by signal staleness (h since last update),
                            with separate panels per days_out bucket
"""
from __future__ import annotations

import sys
from collections import defaultdict
from pathlib import Path

import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
import numpy as np

from plot_common import REPO_ROOT, load, find_csv


def _find_csv(base: Path) -> Path:
    """Find transaction_summary.csv under base, searching run subdirs too."""
    direct = base / "transaction_summary.csv"
    if direct.exists():
        return direct
    # base might be a named instance dir with run_* subdirs — look one level up
    global_csv = REPO_ROOT / "output" / "transaction_summary.csv"
    if global_csv.exists():
        return global_csv
    raise FileNotFoundError(f"No transaction_summary.csv found under {base}")


def _scatter_bar(ax_scatter, ax_bar, xs, returns, colours, all_x, label: str, xlabel: str):
    for colour, lbl in [("green", "profit"), ("red", "loss"), ("steelblue", "sold early")]:
        mask = colours == colour
        if mask.any():
            ax_scatter.scatter(xs[mask], returns[mask], c=colour, alpha=0.5, s=30, label=lbl)
    ax_scatter.axhline(0, color="black", linewidth=0.8, linestyle="--")
    ax_scatter.set_ylabel("Return %")
    ax_scatter.set_title(label)
    ax_scatter.legend(fontsize=7)

    bucket: dict[float, list] = defaultdict(list)
    for x, r in zip(xs, returns):
        bucket[x].append(r)

    means  = [np.mean(bucket.get(x, [0])) for x in all_x]
    counts = [len(bucket.get(x, [])) for x in all_x]
    bcolours = ["green" if m >= 0 else "red" for m in means]
    bars = ax_bar.bar(all_x, means, color=bcolours, alpha=0.7)
    for bar, cnt in zip(bars, counts):
        if cnt:
            ax_bar.text(bar.get_x() + bar.get_width() / 2,
                        bar.get_height() + (3 if bar.get_height() >= 0 else -8),
                        str(cnt), ha="center", va="bottom", fontsize=7)
    ax_bar.axhline(0, color="black", linewidth=0.8, linestyle="--")
    ax_bar.set_xlabel(xlabel)
    ax_bar.set_ylabel("Mean return %")


def plot_by_hour(rows: list[dict], label: str, out_path: Path) -> None:
    hours   = np.array([r["hour"] for r in rows])
    returns = np.array([r["return_pct"] for r in rows])
    colours = np.array([
        "green" if r["return_pct"] > 0 else
        "red"   if r["return_pct"] < 0 else
        "steelblue"
        for r in rows
    ])
    all_hours = list(range(24))

    fig, (ax1, ax2) = plt.subplots(2, 1, figsize=(14, 9),
                                    gridspec_kw={"height_ratios": [2, 1]})
    _scatter_bar(ax1, ax2, hours, returns, colours, all_hours,
                 f"Return % by hour of purchase — {label}", "Hour of purchase (UTC)")
    ax1.set_xticks(range(24))
    ax2.set_xticks(range(24))
    fig.tight_layout()
    fig.savefig(out_path, dpi=150)
    print(f"Saved: {out_path}")


def plot_by_hour_and_day(rows: list[dict], label: str, out_path: Path) -> None:
    """One column per days_out bucket (local time), x axis = local hour of purchase."""
    def bucket_days(d: float) -> str:
        if d < 0.5:
            return "same day"
        elif d < 1.5:
            return "1 day out"
        else:
            return "2+ days out"

    groups: dict[str, list] = {"same day": [], "1 day out": [], "2+ days out": []}
    for r in rows:
        groups[bucket_days(r["local_days_out"])].append(r)

    all_hours = list(range(24))
    n_cols = sum(1 for g in groups.values() if g)
    if n_cols == 0:
        return

    fig, axes = plt.subplots(2, n_cols, figsize=(7 * n_cols, 9),
                              gridspec_kw={"height_ratios": [2, 1]},
                              squeeze=False)
    fig.suptitle(f"Return % by local hour of purchase — {label}", fontsize=12)

    col = 0
    for day_label in ("same day", "1 day out", "2+ days out"):
        grp = groups[day_label]
        if not grp:
            continue
        hours   = np.array([r["local_hour"] for r in grp])
        returns = np.array([r["return_pct"] for r in grp])
        colours = np.array([
            "green" if r["return_pct"] > 0 else
            "red"   if r["return_pct"] < 0 else
            "steelblue"
            for r in grp
        ])
        ax1, ax2 = axes[0][col], axes[1][col]
        _scatter_bar(ax1, ax2, hours, returns, colours, all_hours,
                     f"{day_label} (n={len(grp)})", "Hour of purchase (city local time)")
        ax1.set_xticks(range(0, 24, 2))
        ax2.set_xticks(range(0, 24, 2))
        col += 1

    fig.tight_layout()
    fig.savefig(out_path, dpi=150)
    print(f"Saved: {out_path}")


def plot_by_staleness(rows: list[dict], label: str, out_path: Path) -> None:
    """
    One column per days_out bucket (0, 1, 2+).
    X axis: staleness in 1-hour bins (0-1h, 1-2h, ..., 5-6h).
    """
    def bucket_days(d: float) -> str:
        if d < 0.5:
            return "same day"
        elif d < 1.5:
            return "1 day out"
        else:
            return "2+ days out"

    groups: dict[str, list] = {"same day": [], "1 day out": [], "2+ days out": []}
    for r in rows:
        groups[bucket_days(r["local_days_out"])].append(r)

    # 1-hour staleness bins: label = floor(staleness)
    all_bins = list(range(6))

    n_cols = sum(1 for g in groups.values() if g)
    if n_cols == 0:
        return

    fig, axes = plt.subplots(2, n_cols, figsize=(6 * n_cols, 9),
                              gridspec_kw={"height_ratios": [2, 1]},
                              squeeze=False)
    fig.suptitle(f"Return % by signal staleness — {label}", fontsize=12)

    col = 0
    for day_label in ("same day", "1 day out", "2+ days out"):
        grp = groups[day_label]
        if not grp:
            continue

        stal = np.array([min(int(r["staleness"]), 5) for r in grp])
        returns = np.array([r["return_pct"] for r in grp])
        colours = np.array([
            "green" if r["return_pct"] > 0 else
            "red"   if r["return_pct"] < 0 else
            "steelblue"
            for r in grp
        ])

        ax1, ax2 = axes[0][col], axes[1][col]
        _scatter_bar(ax1, ax2, stal, returns, colours, all_bins,
                     day_label, "Hours since last forecast update")
        ax1.set_xticks(all_bins)
        ax1.set_xticklabels([f"{b}-{b+1}h" for b in all_bins], fontsize=8)
        ax2.set_xticks(all_bins)
        ax2.set_xticklabels([f"{b}-{b+1}h" for b in all_bins], fontsize=8)
        col += 1

    fig.tight_layout()
    fig.savefig(out_path, dpi=150)
    print(f"Saved: {out_path}")


def _print_summary(rows: list[dict]) -> None:
    print(f"\n{len(rows)} closed positions")
    by_hour: dict[int, list] = defaultdict(list)
    for r in rows:
        by_hour[r["hour"]].append(r["return_pct"])
    print("\nMean return by UTC hour of purchase:")
    for h in sorted(by_hour):
        m = np.mean(by_hour[h])
        n = len(by_hour[h])
        bar = "█" * min(int(abs(m) / 5), 30)
        sign = "-" if m < 0 else "+"
        print(f"  {h:02d}:xx  {m:+7.1f}%  n={n:3d}  {sign}{bar}")


def main() -> None:
    args = sys.argv[1:]
    explicit_csv = None
    out_dir = None

    if "--csv" in args:
        i = args.index("--csv")
        explicit_csv = Path(args[i + 1])
        args = args[:i] + args[i + 2:]

    if "--out" in args:
        i = args.index("--out")
        out_dir = Path(args[i + 1])
        args = args[:i] + args[i + 2:]

    positional = [a for a in args if not a.startswith("--")]

    if explicit_csv:
        csv_path = explicit_csv
    elif positional:
        csv_path = _find_csv(Path(positional[0]))
    else:
        csv_path = _find_csv(REPO_ROOT / "output")

    print(f"Loading: {csv_path}")
    rows = load(csv_path)
    if not rows:
        print("No closed positions found.")
        return

    label   = csv_path.parent.name
    out_dir = out_dir or csv_path.parent
    out_dir.mkdir(parents=True, exist_ok=True)

    plot_by_hour(rows, label, out_dir / "return_by_hour.png")
    plot_by_hour_and_day(rows, label, out_dir / "return_by_hour_by_day.png")
    plot_by_staleness(rows, label, out_dir / "return_by_staleness.png")
    _print_summary(rows)


if __name__ == "__main__":
    main()
